# Generated by Django 3.2.9 on 2022-01-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Something big for the input of any project'),
            preserve_default=False,
        ),
    ]
