# Generated by Django 3.2.9 on 2022-01-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220114_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='is_ordered',
        ),
    ]
